apiVersion: v1
kind: Service
metadata:
  name: car-prediction-loadbalancer
spec:
  selector:
    app: car-prediction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
  type: LoadBalancer
